spring:
  application:
    name: cheap-shop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zc457825900/config-repo     # 配置git仓库的地址
          search-paths: config-repo                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 457825900@qq.com                          # git仓库的账号
          password: hellomyzc123

server:
  port: 8012

